#! /bin/sh

set -ueo pipefail

versions=(
    "8_10_7"
    "9_0_2"
    "9_2_1"
)

SEP="------------------------------------------------------------"

for version in "${versions[@]}"; do
    echo $SEP
    nix-shell \
        --pure \
        --argstr ghc "$version" \
        --run "ghc --version && cabal test all -fvalidate"
done

echo $SEP
