name: Validate

on:
  push:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Install Nix
      uses: cachix/install-nix-action@v16

    - name: Cachix
      uses: cachix/cachix-action@v10
      with:
        name: elderephemera
        skipPush: true
        extraPullNames: ghc

    - name: Cache Cabal Store
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ hashFiles('**/*.cabal') }}

    - name: Validate
      run: |
        nix-shell --run 'cabal update'
        ./validate
